permalink: '/blog/:year/:month/:day/:slug'
baseurl: ''
url: ''
title: LTUX
about_blob:
  LTUX is an annual campus-wide expo at Lawrence Technological University that
  combines anime, games, and eSports events to present the latest and greatest
  student projects, local game developers, business partners, cosplay
  competitions, eSports tournaments, talks, panels, and more! Advised by
  Assistant Professor of Game Design Mars Ashton & Game Software Development
  Lecturer Jose Gonzalez-Belmonte, student leaders pool their resources together
  each year to provide a free celebration of everything LTU has to offer. Great
  work, a friendly and welcoming studio culture, and amazing potential.
  <br/><br/>
  This year, LTU Expo is fully online, starting Monday April, 19th at 6:00 PM and running until Saturday, April 24th at 11:59 PM. Watch keynote speakers discuss their experience working in the gaming industry, root for your favorite team in the exciting Esports competition, and try the latest and greatest indie games from our amazing students and local developers. Events include panels, indie game demos, an ExtraLife 24-hour charity stream, and more! Pop in our Discord to interact with other attendees and join the fun. The entire event will be streamed on <a target='_blank' href='https://www.twitch.tv/statechampsesports'>https://www.twitch.tv/statechampsesports</a>.
  <br/><br/>
  <a target='_blank' href='https://www.extra-life.org/participant/Infinite-Machinev'>https://www.extra-life.org/participant/Infinite-Machine</a>
copyright_name: LTUX
contact_email: support@ltux.games
masthead_tile_text: LTUX Gaming Convention
start_date: 'April 23rd 2022'
end_date: 'April 23rd 2022'
start_date_code: '2022/04/23'
end_date_code: '2022/04/23'
twitter: 'https://twitter.com/LTUExpo'
facebook: 'https://www.facebook.com/ltuexpo'
linkedin: 'https://www.linkedin.com/company/ltux'
email_subscribe: null
twitch_channel_main: 'statechampsesports'
twitch_channel_charity: 'infinitemachineltu'
paginate: 5
paginate_path: '/blog/post:num/'
excerpt_separator: <!--more-->
sass:
  style: compressed
  sass_dir: css
collections:
  organizers:
    output: false
  games:
    output: false
  speakers:
    output: true
  schedule:
    output: false
plugins:
  - jekyll-feed
  - jekyll-paginate
