permalink: '/blog/:year/:month/:day/:slug'
baseurl: ''
url: ''
title: LTUX
about_blob:
  LTUX is a FREE annual campus-wide expo at Lawrence Technological University that combines anime, games, and Esports to showcase local talent in the form of local game showcases, cosplay workshops, gaming tournaments, panels, vendors, and more!
  <br/><br/>
  Advised by faculty members Professor Jose Gonzalez-Belmonte, Dr. Stephen Mallory, and Dr. Ahu Yolac, student leaders & alumni pool their resources together each year to provide a free celebration of everything LTU and Michigan has to offer. Great work, a friendly and welcoming studio culture, and amazing potential.
  <br/><br/>
  This year, we plan to be bigger and better than ever before! Come see keynote speakers discuss their experience working in the gaming industry, play games, browse the work of local talent, eat delicious food, and try the latest games from our amazing students and local developers. 
  <br/><br/>
  Events include panels, indie game demos, an ExtraLife charity stream, an Escape Room, Psychic Drive Arcade, and more! Pop in our Discord to interact with other attendees and join the fun. Watch here and our socials below for updates to come!
  <br/><br/>
  <b><h4 style="color:#FF0000;">OUR SITE WILL BE GOING THROUGH UPDATES OVER THE COMING WEEKS, SO THANK YOU FOR YOUR PATIENCE WHILE WE MAKE THESE MUCH NEEDED CHANGES!</h4></b>
copyright_name: LTUX
contact_email: support@ltux.games
masthead_tile_text: LTUX Games, Esports, and Anime Convention
start_date: 'April 27th 2024, 10:00 AM - 7:00 PM'
end_date: 'April 27th 2024'
start_date_code: '2024/04/27'
end_date_code: '2024/04/27'
twitter: 'https://twitter.com/LTUExpo'
facebook: 'https://www.facebook.com/ltuexpo'
linkedin: 'https://www.linkedin.com/company/ltux'
discord: 'https://discord.gg/K52X6HT'
email_subscribe: null
twitch_channel_main: 'statechampsesports'
twitch_channel_charity: 'infinitemachineltu'
paginate: 5
paginate_path: '/blog/post:num/'
excerpt_separator: <!--more-->
sass:
  style: compressed
  sass_dir: css
collections:
  organizers:
    output: false
  games:
    output: false
  speakers:
    output: true
  schedule:
    output: false
  sponsors:
    output: false
  vendors:
    output: false
  vendors-food:
    output: false
defaults:
  - scope:
      path: "img"
    values:
      image: true
plugins:
  - jekyll-feed
  - jekyll-paginate
