permalink: '/blog/:year/:month/:day/:slug'
baseurl: ''
url: ''
title: LTUX
about_blob:
  LTUX is an annual campus-wide expo at Lawrence Technological University that
  combines anime, games, and eSports events to present the latest and greatest
  student projects, local game developers, business partners, cosplay
  competitions, eSports tournaments, talks, panels, and more! Advised by
  Game Software Development Senior Lecturer Jose Gonzalez-Belmonte & Assistant Professors
  of Game Design Ahu Yolac & Stephen Mallory, student leaders pool their resources together
  each year to provide a free celebration of everything LTU has to offer. Great
  work, a friendly and welcoming studio culture, and amazing potential.
  <br/><br/>
  This year, LTU Expo is back in person for the first time in two years! Come see keynote speakers discuss 
  their experience working in the gaming industry, play some physical (board, card, etc) and video games, 
  and try the latest and greatest indie games from our amazing students and local developers. Events include panels, indie game demos, 
  an ExtraLife charity stream, and more! Pop in our Discord to interact with 
  other attendees and join the fun. The entire event will also be streamed on twitch, so if you can't make it, don't worry! Watch here
  and our socials below for updates to come!
copyright_name: LTUX
contact_email: support@ltux.games
masthead_tile_text: LTUX Gaming Convention
start_date: 'April 23rd 2022'
end_date: 'April 23rd 2022'
start_date_code: '2022/04/23'
end_date_code: '2022/04/23'
twitter: 'https://twitter.com/LTUExpo'
facebook: 'https://www.facebook.com/ltuexpo'
linkedin: 'https://www.linkedin.com/company/ltux'
email_subscribe: null
twitch_channel_main: 'statechampsesports'
twitch_channel_charity: 'infinitemachineltu'
paginate: 5
paginate_path: '/blog/post:num/'
excerpt_separator: <!--more-->
sass:
  style: compressed
  sass_dir: css
collections:
  organizers:
    output: false
  games:
    output: false
  speakers:
    output: true
  schedule:
    output: false
plugins:
  - jekyll-feed
  - jekyll-paginate
